ci linter fix

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -34,4 +34,10 @@ jobs:
         uv add ruff
     
     - name: Run Ruff
-      run: uv run ruff check
+      run: |
+        OUTPUT=$(uv run ruff check)
+          echo "$OUTPUT"
+          if [[ "$OUTPUT" != *"All checks passed!"* ]]; then
+            echo "Linter Failure."
+            exit 1
+          fi
